version: "3"

services:
  archiver-viewer:
    deploy:
      mode: replicated
      replicas: 1
    image: httpd:2.4.35
    ports:
      - "80:80"
    volumes:
      - "/home/carneirofc/archiver-viewer/dist:/usr/local/apache2/htdocs/archiver-viewer"

