version: "3.7"
services:
  devel:
    image: node:15.14.0-buster
    working_dir: /viewer
    user: "1000:1000"
    command: bash -c 'set -x; [[ ! -d node_modules || "$FORCE_INSTALL"=true ]] && npm install --loglevel verbose; npm run start;'
    stdin_open: true # without this node doesn't start
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      FORCE_INSTALL: "false"
    volumes:
      - ".:/viewer"

  release:
    image: lnlscon/archiver-viewer:2021-04-29-be6b745
    ports:
      - 80:80
